### ISSUE TITLE
Open the modal even if the current page is a new tab page

### ISSUE THREAD

**Issue by krishna-kb** [Blagoj5/Tab-Master#12]
When I am on the new tab page with no other tabs / url open, I would like to open the modal and navigate to an item in the history.

Expected: Modal should open on the new tab page.

Actual: Modal doesn't open on the new tab page

**Comment by Blagoj5** [comment]
Thanks for reporting this, I'm aware of this and this is actually added in the notes when you install the extension (the main problem is that Chrome does not allow this):

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/50581470/160695327-278b2308-de3e-4d64-89b7-c4d5f63c509b.png">

- **Note:** Google has not designed extensions like Tab-Master to run on this Chrome Web Store page and Chrome's new tab page. sorry! 

- **Note:** Chrome has some warning messages about the permissions required to run Tab-Master. In fact, Tab-Master's Javascript needs to be loaded on each page. please do not worry. Tab-Master never communicates with the server and does nothing to the data. Everyone is free to read the open source if interested.

### Potential solution

From your feedback I might consider:

- Use the popup tab-master configuration to show the modal and enable this wanted navigation (this will take quite some time to implement so **please** be patient for now). With this behavior, you'll be able to navigate, but the modal will be an options popup in the right corner

**Comment by krishna-kb** [comment]
Oops, totally missed the note on the extension page. Sorry for that.
Please take your time to build the feature you mentioned in the last point.
Will surely try to contribute if I find some time.
Thanks for building such an awesome extension, it has a good utility value. 🙏🏻
