### ISSUE TITLE
The digit zero under the search bar

### ISSUE THREAD

**Issue by duklin** [Blagoj5/Tab-Master#4]
Great work on the extension @Blagoj5 
![Screenshot 2022-01-27 at 13 01 51](https://user-images.githubusercontent.com/22457392/151355401-53e834d3-0213-46da-ae6f-09d463c227d8.png)

As you can see from the screenshot, there is the '0' under the search bar. Does it have a meaning? I don't see it in the demo.

**Comment by Blagoj5** [comment]
@duklin thanks for the feedback, it seems like an older dev version was deployed instead of the recent one. This should be fixed in `1.0.1` version of this extension which is currently in review. After it's published please test it out and close this issue if everything is working correctly.
